from . import academic_year
from . import grade_level
from . import school_class
from . import subject
from . import parent
from . import teacher
from . import student
from . import attendance
from . import exam
from . import timetable
from . import fee
from . import transport
from . import hostel
from . import library
